---
version: "3.4"
services:
  database:
    restart: always
    image: postgres:12
    container_name: herdbook-db
    env_file:
      - ./.docker/database-variables.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  main-load-db:
    image: herdbook_main_load_db
    entrypoint: sleep 1h
    build:
      context: ./
      dockerfile: ./.docker/main-load-db
    container_name: herdbook-main-load-db
    env_file:
      - ./.docker/database-variables.env
    volumes:
      - type: bind
        source: ./scripts
        target: /scripts
    depends_on:
      - database
