---

version: "3.4"
services:
    database:
        restart: always
        image: postgres:12
        container_name: herdbook-db
        environment:
            - POSTGRES_DB=herdbook
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-insecure}
            - POSTGRES_USER=herdbook
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    api:
        image: herdbook_api
        build:
            context: ./
            dockerfile: .docker/api
        container_name: herdbook-api
    herdbook-frontend-devel:
        image: herdbook_frontend:latest
        build:
            context: ./
            dockerfile: .docker/frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
    main:
        image: herdbook_main
        build:
            context: ./
            dockerfile: .docker/main
        container_name: herdbook-main
        ports:
            - 8080:8080
            - 8443:8443
        volumes:
            - type: bind
              source: ./app
              target: /api_src
            - type: bind
              source: ./config
              target: /config
        depends_on:
            - database
            - herdbook-frontend-devel
