---
version: "3.4"
services:
    database:
        restart: always
        image: postgres:12
        container_name: herdbook-db
        env_file:
            - ./.docker/database-variables.env
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    herdbook-frontend-devel:
        image: herdbook_frontend
        build:
            context: ./
            dockerfile: .docker/frontend
            cache_from:
              - ghcr.io/nbisweden/herdbook_frontend
        volumes:
            - ./frontend:/home/node/app/
            - /home/node/app/node_modules
    main:
        image: herdbook_main
        build:
            context: ./
            dockerfile: .docker/main
            cache_from:
              - ghcr.io/nbisweden/herdbook_main
        container_name: herdbook-main
        env_file:
            - ./.docker/database-variables.env
            - ./.docker/r-api-variables.env
        ports:
            - 8080:8080
            - 8443:8443
        volumes:
            - type: bind
              source: ./app
              target: /api_src
            - type: bind
              source: ./config
              target: /config
        depends_on:
            - database
            - herdbook-frontend-devel
    r-api:
        container_name: r-api
        build:
            context: ./
            dockerfile: .docker/r-api
            cache_from:
              - ghcr.io/nbisweden/herdbook_r-api
        env_file:
            - ./.docker/database-variables.env
            - ./.docker/r-api-variables.env
        image: herdbook_r-api
        volumes:
            - type: bind
              source: ./R
              target: /code
 
