---
version: "3.4"
services:
    database:
        restart: always
        image: postgres:12
        container_name: herdbook-db
        env_file:
            - ./.docker/database-variables.env
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    main:
        image:  ghcr.io/nbisweden/herdbook_main:${TAG:?TAG-not-set}
        container_name: herdbook-main
        env_file:
            - ./.docker/database-variables.env
            - ./.docker/r-api-variables.env
            - ./.docker/main-api-variables.env
        ports:
            - 80:8080
            - 443:8443
            - 9090:9090
        volumes:
            - type: bind
              source: ./app
              target: /api_src
            - type: bind
              source: ./config
              target: /config
            - type: bind
              source: ./logs
              target: /logs
        depends_on:
            - database
            - r-api
        restart: always

    r-api:
        image: ghcr.io/nbisweden/herdbook_r-api:${TAG:?TAG-not-set}
        container_name: r-api
        env_file:
            - ./.docker/database-variables.env
            - ./.docker/r-api-variables.env
        restart: always
