#!/bin/bash

if [ -e /data/db_is_set_up ]; then
    echo "Database is set up already, skipping"
    exit 0
fi

if [ -n "$PGPASS" ] ;then
   echo "$PGHOST:5432:$PGDATABASE:$PGUSER:$PGPASS" > ~/.pgpass
   chmod og-rwx ~/.pgpass
fi
   
for p in {1..20}; do
  sleep 10
  if psql -f /sql/schema.sql ; then
      echo "Loaded database correctly"
      touch /data/db_is_set_up
    exit 0
  fi
done

echo "Failed to load database"
exit 1
