name: Create packages
on:
  push:
    branches:


jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
        run: |
             echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin

             branch=${GITHUB_REF##*/}
             
             for image in r-api herdbook_main herdbook_frontend; do
               docker pull ghcr.io/nbisweden/${image}:latest || true
               docker pull "ghcr.io/nbisweden${image}:$branch" || true
             done
             
             for p in .docker/*.default ; do
               mv "$p" "${p%.default}"
             done

             docker-compose build
             
             docker tag r-api:latest ghcr.io/nbisweden/r-api:"$branch"
             docker tag herdbook_main:latest ghcr.io/nbisweden/herdbook_main:"$branch"
             docker tag herdbook_frontend:latest ghcr.io/nbisweden/herdbook_frontend:"$branch"

             docker push ghcr.io/nbisweden/r-api:"$branch"
             docker push ghcr.io/nbisweden/herdbook_main:"$branch" 
             docker push ghcr.io/nbisweden/herdbook_frontend:"$branch" 

             if [ master = "$branch" ]; then
               docker tag r-api:latest ghcr.io/nbisweden/r-api:latest
               docker tag herdbook_main:latest ghcr.io/nbisweden/herdbook_main:latest
               docker tag herdbook_frontend:latest ghcr.io/nbisweden/herdbook_frontend:"latest

               docker push ghcr.io/nbisweden/r-api:latest
               docker push ghcr.io/nbisweden/herdbook_main:latest"
               docker push ghcr.io/nbisweden/herdbook_frontend:latest 
             fi
