---

name: Run lint on push
on: push

jobs:
  lintonpush:
# We need to pull yarn from another source anyway, use 16.04 to lower amount of upgrades needed
    runs-on: ubuntu-16.04
    steps:
      - name: Get the code
        uses: actions/checkout@v2

# Avoid running into issues because of out-of-sync by doing a upgrade

      - name: Run apt-get update
        run: sudo apt-get update

      - name: Remove packages we don't care for
        run: sudo apt-get remove php.* dotnet.* mono.* mysql.* libmono.*

      - name: Run apt-get dist-upgrade -y
        run: sudo apt-get dist-upgrade -y

      - name: Get and add key for yarn
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

      - name: Setup repo for yarn
        run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

      - name: Run apt-get update again to pick up yarn
        run: sudo apt-get update

      - name: Install yarn
        run: 'sudo apt-get -f -y install yarn'

      - name: Grab packages
        working-directory: frontend 
        run: cd frontend && yarnpkg install

      - name: Do the lint
        working-directory: frontend
        run: find . -name '*.tsx' -print0 | xargs -0 yarnpkg run eslint || true
